[package]
name = "my_first_rust"
version = "1.2.3"
authors = ["Serhii Stepanenko"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
